kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cilium-testing
networking:
  disableDefaultCNI: true
  kubeProxyMode: none   
nodes:
- role: control-plane
- role: worker
  labels:
    technat.dev/egress-node: true
- role: worker
  labels:
    technat.dev/egress-node: true
- role: worker
  labels:
    technat.dev/egress-node: true
- role: worker
- role: worker
- role: worker