
cluster:
  name: ${cluster_name}

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

eni:
  enabled: true
ipam:
  mode: eni
routingMode: "native"
# egressMasqueradeInterfaces: eth0
bpf:
  masquerade: true

kubeProxyReplacement: strict
k8sServicePort: 443
k8sServiceHost: ${cluster_endpoint}

operator:
  replicas: 1

enterprise:
  # -- Enables egress gateway HA
  egressGatewayHA:
    enabled: true
    # -- Install egress gateway IP rules and routes in order to properly steer
    # egress gateway traffic to the correct ENI interface
    installRoutes: false
    # -- Time between triggers of egress gateway state reconciliations
    reconciliationTriggerInterval: 1s
    # -- Maximum number of entries in egress gateway policy map
    # maxPolicyEntries: 16384
    # -- Healthcheck timeout after which an egress gateway is marked not healthy.
    # This also configures the frequency of probes to a value of healthcheckTimeout / 2
    # healthcheckTimeout: 2s



