cluster:
  name: ${name}

hubble:
  relay: 
    enabled: true
  ui:
    enabled: true
eni:
  enabled: true
ipam:
  mode: eni

tunnel: disabled
enableIPv4Masquerade: false

kubeProxyReplacement: strict
k8sServicePort: 6443
k8sServiceHost: ${cluster_endpoint}

operator:
  replicas: 1

egressGateway:
  enabled: true
  installRoutes: true

bpf:
  masquerade: true

l7Proxy: false