cluster:
  name: ${cluster_name}

hubble:
  relay: 
    enabled: true
  ui:
    enabled: true

eni:
  enabled: true
ipam:
  mode: eni
routingMode: "native"
egressMasqueradeInterfaces: eth0

kubeProxyReplacement: strict
k8sServicePort: 443
k8sServiceHost: ${cluster_endpoint}

operator:
  replicas: 1

egressGateway:
  enabled: true
  installRoutes: true

bpf:
  masquerade: true

l7Proxy: false