cluster:
  name: cilium-testing

ipam:
  mode: kubernetes

routingMode: "tunnel"
tunnelProtocol: vxlan

bpf:
  masquerade: true

kubeProxyReplacement: strict
k8sServicePort: 6443
k8sServiceHost: cilium-testing-control-plane

hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

operator:
  replicas: 1

enterprise:
  # -- Enables egress gateway HA
  egressGatewayHA:
    enabled: true
    # -- Install egress gateway IP rules and routes in order to properly steer
    # egress gateway traffic to the correct ENI interface
    installRoutes: false
    # -- Time between triggers of egress gateway state reconciliations
    reconciliationTriggerInterval: 1s
    # -- Maximum number of entries in egress gateway policy map
    # maxPolicyEntries: 16384
    # -- Healthcheck timeout after which an egress gateway is marked not healthy.
    # This also configures the frequency of probes to a value of healthcheckTimeout / 2
    # healthcheckTimeout: 2s



