cluster:
  name: ${cluster_name}

hubble:
  relay: 
    enabled: true
  ui:
    enabled: true

eni:
  enabled: true
ipam:
  mode: eni
routingMode: "native"

kubeProxyReplacement: strict
k8sServicePort: 443
k8sServiceHost: ${cluster_endpoint}

operator:
  replicas: 1

l7Proxy: false
bpf:
  masquerade: true
enableIPv4Masquerade: true
egressGateway:
  enabled: true
  installRoutes: true