cluster:
  name: kind-cilium-testing
ipam:
  mode: kubernetes

operator:
  replicas: 1

routingMode: tunnel
tunnelProtocol: vxlan

kubeProxyReplacement: strict
k8sServiceHost: cilium-testing-control-plane
k8sServicePort: 6443  

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

bpf:
  masquerade: true

l7Proxy: false

egressGateway:
  enabled: true