---
apiVersion: v1
kind: Namespace
metadata:
  name: egress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortio
  name: fortio
  namespace: egress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  strategy: {}
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - image: fortio/fortio
        name: fortio
        args:
        - load 
        - -t=0
        - -a
        - -logger-force-color 
        # - http://external-example-service.default.svc.cluster.local
        - http://172.18.0.9
---
apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: egress
        

  # Specify which destination CIDR(s) this policy applies to.
  # Multiple CIDRs can be specified.
  destinationCIDRs:
  - "0.0.0.0/0"

  egressGroups:
  - nodeSelector:
      matchLabels:
        technat.dev/egress-node: "true"
        # node.kubernetes.io/name: cilium-testing-worker

    # Specify the IP address used to SNAT traffic matched by the policy.
    # It must exist as an IP associated with a network interface on the instance.
    egressIP: 172.18.0.100

    # Alternatively it's possible to specify the interface to be used for egress traffic.
    # In this case the first IPv4 assigned to that interface will be used as egress IP.
    # interface: eth0
